const fill_color = {fill: "lightblue"};
const fill_color1 = {fill: "#69d2ff"};
const fill_color2 = {fill: "#99d8ff"};
const statesCustomConfig = () => {
    return {
      "NJ": fill_color,
      "NY": fill_color2,
      "WY": fill_color,
      "AL": fill_color2,
      "AK": fill_color2,
      "AR": fill_color1,
      "AZ": fill_color2,
      "CA": fill_color1,
      "CO": fill_color,
      "CT": fill_color2,
      "DE": fill_color,
      "FL": fill_color1,
      "GA": fill_color2,
      "HI": fill_color1,
      "ID": fill_color,
      "IO": fill_color2,
      "IN": fill_color,
      "IA": fill_color1,
      "KS": fill_color2,
      "KY": fill_color1,
      "LA": fill_color,
      "ME": fill_color2,
      "MD": fill_color,
      "MA": fill_color1,
      "MI": fill_color2,
      "MN": fill_color1,
      "MS": fill_color,
      "MO": fill_color2,
      "MT": fill_color1,
      "NE": fill_color,
      "NV": fill_color2,
      "NH": fill_color1,
      "NJ": fill_color,
      "IL": fill_color2,
      "NM": fill_color,
      "NY": fill_color1,
      "NC": fill_color2,
      "ND": fill_color1,
      "OH": fill_color,
      "OK": fill_color2,
      "OR": fill_color,
      "PA": fill_color1,
      "RI": fill_color2,
      "SC": fill_color1,
      "SD": fill_color,
      "TN": fill_color2,
      "TX": fill_color,
      "UT": fill_color1,
      "VT": fill_color2,
      "VA": fill_color1,
      "WA": fill_color,
      "WV": fill_color2,
      "WI": fill_color,
      "WY": fill_color1,      
    };
  };

  export default statesCustomConfig;